services:
  backend:
    build:
      context: ./backend/app
    ports:
      - "8000:8000"
    env_file:
      - .env  
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/kitchenware
    ports:
      - "8080:80"  
    restart: unless-stopped

