from dotenv import load_dotenv
import os

__all__ = ['JWT_SECRET_KEY', 'JWT_ALGORITHM', 'ACCESS_TOKEN_EXPIRATION_TIME', 'REFRESH_TOKEN_EXPIRATION_TIME']

load_dotenv()

JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY')
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM')

ACCESS_TOKEN_EXPIRATION_TIME = int(os.getenv('ACCESS_TOKEN_EXPIRATION_TIME'))
REFRESH_TOKEN_EXPIRATION_TIME = int(os.getenv('REFRESH_TOKEN_EXPIRATION_TIME')) 